'use client'
import { useCallback } from 'react'
import './css/globals.css'
import { Inter } from 'next/font/google'
import { GoogleOAuthProvider } from '@react-oauth/google'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <GoogleOAuthProvider clientId="125984775541-023rp3fhq6n6gvngqp9ortsf58rsl5uu.apps.googleusercontent.com">
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </GoogleOAuthProvider>
  )
}
