'use client'
import { useCallback } from 'react'
import './css/globals.css'
import config from './config.json'
import { Inter } from 'next/font/google'
import { GoogleOAuthProvider } from '@react-oauth/google'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId={config.CLIENT_ID}>
        <body className={inter.className}>{children}</body>
      </GoogleOAuthProvider>
    </html>
  )
}
