"use client";

import { ArrowLeft } from "lucide-react";
import { useRouter } from "next/navigation";


export default function PrivacyPolicy() {
  const router = useRouter();
  return (
    <div className="max-w-4xl mx-auto px-4 py-16">
      {/* Back Button */}
      <button
        onClick={() => router.push("/")}
        className="mb-8 flex items-center gap-2 text-gray-600 hover:text-indigo-600 transition-colors group"
      >
        <ArrowLeft className="w-5 h-5 transition-transform group-hover:-translate-x-1" />
        <span>Back</span>
      </button>
      <h1 className="text-3xl font-bold mb-8 bg-gradient-to-r from-indigo-600 to-purple-600 text-transparent bg-clip-text">
        Privacy Policy
      </h1>
      Copy{" "}
      <div className="space-y-6 text-gray-600">
        <section>
          <h2 className="text-xl font-semibold text-gray-800 mb-3">
            1. Information We Collect
          </h2>
          <p>
            Todue collects specific personal information necessary for providing
            our service. By using Todue, you agree to the collection and use of
            your information as described in this Privacy Policy.
          </p>
          <ul className="list-disc pl-6 mt-2 space-y-2">
            <li>Email address used for account authentication</li>
            <li>Unique user identifier generated by our system</li>
            <li>Courses and assignments you create</li>
            <li>Timestamps of course and assignment creation</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-800 mb-3">
            2. How We Use Your Information
          </h2>
          <p>We use the information we collect for the following purposes:</p>
          <ul className="list-disc pl-6 mt-2 space-y-2">
            <li>Authentication and account management</li>
            <li>
              Enabling you to create, view, update, and delete your courses and
              assignments
            </li>
            <li>Providing a personalized user experience</li>
            <li>Ensuring data security and access control</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-800 mb-3">
            3. Data Protection and Security
          </h2>
          <p>
            Todue is committed to protecting your personal information through
            robust security measures:
          </p>
          <ul className="list-disc pl-6 mt-2 space-y-2">
            <li>All user data is stored securely in our database</li>
            <li>Implemented Row Level Security to isolate user data</li>
            <li>Each user can only access their own courses and assignments</li>
            <li>User identification uses secure UUID-based authentication</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-800 mb-3">
            4. User Data Access and Control
          </h2>
          <p>
            We provide you with complete control over your personal information:
          </p>
          <ul className="list-disc pl-6 mt-2 space-y-2">
            <li>View your own courses and assignments</li>
            <li>Create new courses and assignments</li>
            <li>Update existing courses and assignments</li>
            <li>Delete courses and assignments at any time</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-800 mb-3">
            5. Third-Party Access and Sharing
          </h2>
          <p>Todue maintains strict privacy standards regarding your data:</p>
          <ul className="list-disc pl-6 mt-2 space-y-2">
            <li>
              We do not share your personal information with third parties
            </li>
            <li>
              Exceptions may include legal requirements or protecting our rights
            </li>
            <li>Any data sharing will be done with your explicit consent</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-800 mb-3">
            6. Data Retention
          </h2>
          <p>Your data is stored and managed with the following principles:</p>
          <ul className="list-disc pl-6 mt-2 space-y-2">
            <li>
              Courses and assignments are stored while your account is active
            </li>
            <li>You can delete your data at any time</li>
            <li>
              Deleting a course automatically removes associated assignments
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-800 mb-3">
            7. Children's Privacy
          </h2>
          <p>
            Todue is not intended for children under 13. We do not knowingly
            collect personal information from children under this age. If we
            become aware that we have collected such information, we will take
            steps to remove it.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-800 mb-3">
            8. Policy Changes
          </h2>
          <p>
            We may update this Privacy Policy from time to time. We will notify
            you of any changes by posting the new policy on this page. Your
            continued use of Todue after changes constitutes acceptance of the
            new Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-800 mb-3">
            9. Contact Us
          </h2>
          <p>
            If you have any questions about this Privacy Policy, please contact
            us at privacy@todue.com.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-800 mb-3">
            10. Consent
          </h2>
          <p>
            By using Todue, you consent to the terms of this Privacy Policy and
            our handling of your personal information as described herein.
          </p>
        </section>

        <section className="pt-6">
          <p className="text-sm text-gray-500">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </section>
      </div>
    </div>
  );
}